blank_issues_enabled: false
contact_links:
    - name: ğŸ’¬ Discussion Forum | è®¨è®ºåŒº
      url: https://github.com/Moyf/yearly-glance/discussions
      about: Please ask general questions here | è¯·åœ¨è¿™é‡Œæå‡ºä¸€èˆ¬æ€§é—®é¢˜
